version: "3.4"

services:
  ib-gateway:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      TWS_USERID: ${TWS_USERID}
      TWS_PASSWORD: ${TWS_PASSWORD}
      TRADING_MODE: ${TRADING_MODE:-paper}
      READ_ONLY_API: ${READ_ONLY_API:-}
      IB_AUTO_CLOSE_DOWN: ${IB_AUTO_CLOSE_DOWN}
      CLOSE_DOWN_AT: ${CLOSE_DOWN_AT}
      VNC_SERVER_PASSWORD: ${VNC_SERVER_PASSWORD:-}
      TZ: America/Chicago
    secrets:
      - iTraderBot_UID
      - iTraderBot_PWD
    ports:
      - "4001:4001"
      - "4002:4002"
      - "5900:5900"
networks:
    default:
        name: iTradeBotNetwork