version: "3.4"

services:
  ib-gateway:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      TWS_USERID: ${TWS_USERID}
      TWS_PASSWORD: ${TWS_PASSWORD}
      FIX_USERID: ${FIX_USERID:-}
      FIX_PASSWORD: ${FIX_PASSWORD:-}
      TRADING_MODE: ${TRADING_MODE:-paper}
      READ_ONLY_API: ${READ_ONLY_API:-}
      VNC_SERVER_PASSWORD: ${VNC_SERVER_PASSWORD:-}
    ports:
      - "127.0.0.1:4001:4001"
      - "127.0.0.1:4002:4002"
      - "127.0.0.1:4010:4010"
      - "127.0.0.1:5900:5900"
