name: "Publish Docker"

on:
  release:
    types: [published]
  push:
    tags:
      - "ibgateway-*"

jobs:
  publish-docker:
    name: Publish Docker Image
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Extract release channel
        id: channel
        run: |
          channel=$(cut -d - -f 2 <<< "${{ github.ref_name }}")
          echo "::set-output name=channel::$channel"
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/unusualalpha/ib-gateway
          flavor: |
            latest=false
          tags: |
            type=match,pattern=@(\d+.\d+),group=1
            type=match,pattern=@(\d+.\d+.\w+),group=1
            type=match,pattern=ibgateway-(stable|latest),group=1

      - name: Log in to the Container registry
        uses: docker/login-action@17f28ab24d0d2832d5ff23a1409bbfc373ebcb96
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ steps.channel.outputs.channel }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
